### ISSUE TITLE
working with start and endpoints without random

### ISSUE THREAD

**Issue by pacnload** [Py-Project/Bitcoin-wallet-cracker#13]
is there maybe a way that i can set a start and an endpoint to the script without using random? and can i maybe directly save then to an txt file that split every 100mb?

there is a bitcoin puzzle chalenge i need to find a key between
0000000000000000000000000000000000000000000000007cce5efdaccf6808
and
000000000000000000000000000000000000000000000001a838b13505b26867 

i know that i must generate billion of keys but maybe is it possible with some changes on your script? thx

**Comment by adrijano** [comment]
yes it is
