### ISSUE TITLE
Failed to execute script bc

### ISSUE THREAD

**Issue by 123ysys** [Py-Project/Bitcoin-wallet-cracker#15]
Error happened that shows as the title in the message box.
In the running program, it shows as the screenshot.
![bitissue](https://user-images.githubusercontent.com/27964272/115114668-1550fb80-9fc3-11eb-8025-9543af4c1cf1.PNG)

**Comment by adrijano** [comment]
you didnt select file password file

**Comment by 123ysys** [comment]
> you didnt select file password file

So I should get a password file first, right?

**Comment by adrijano** [comment]
yes sir

**Comment by 123ysys** [comment]
> yes sir

Thank you 😊.
