### ISSUE TITLE
Bitcoin addresses

### ISSUE THREAD

**Issue by Axcel763** [Py-Project/Bitcoin-wallet-cracker#6]
Hi! On 'select passwords' Do you use Dictionary as in your gif?

Also is there an alert when an address is found? Where is the txt file? 

I'm looking to break my own. Just wondering if i can just let it crack 1 address. Thanks!

**Comment by Craddock7** [comment]
Yes I do but we charge a 7000 fee

**Comment by sezginyildirim91** [comment]
Open the data-base file with a text editor and delete the contents. You can then add the addresses you want.

**Comment by Axcel763** [comment]
Thank you
