### ISSUE TITLE
hmac problem ?

### ISSUE THREAD

**Issue by freeman5** [Py-Project/Bitcoin-wallet-cracker#8]
Hi, 

I have problem for try this tool, when i want install hmac on windows or debian I get this error on windows :

> Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\freem\AppData\Local\Temp\pip-install-43un5jvm\hashlib_2818bcfc620d42319391f72b9b9f3100\setup.py", line 68
>         print "unknown OS, please update setup.py"
>               ^
>     SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unknown OS, please update setup.py")?
>     ----------------------------------------

and on debian : 

> Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 16, in <module>
>         import setuptools.version
>       File "/usr/local/lib/python3.7/dist-packages/setuptools/version.py", line 1, in <module>
>         import pkg_resources
>       File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 33, in <module>
>         import email.parser
>       File "/usr/lib/python3.7/email/parser.py", line 12, in <module>
>         from email.feedparser import FeedParser, BytesFeedParser
>       File "/usr/lib/python3.7/email/feedparser.py", line 27, in <module>
>         from email._policybase import compat32
>       File "/usr/lib/python3.7/email/_policybase.py", line 9, in <module>
>         from email.utils import _has_surrogates
>       File "/usr/lib/python3.7/email/utils.py", line 28, in <module>
>         import random
>       File "/usr/lib/python3.7/random.py", line 46, in <module>
>         from hashlib import sha512 as _sha512
>       File "/tmp/pip-install-xtn20qsf/hashlib/hashlib.py", line 80
>         raise ValueError, "unsupported hash type"
>                         ^
>     SyntaxError: invalid syntax
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xtn20qsf/hashlib/

and when i click on start : 

![cracker](https://user-images.githubusercontent.com/5463216/108638438-8f677700-748f-11eb-9461-7a4113a925dc.JPG)

**Comment by freeman5** [comment]
not solved after install python3-tk

**Comment by MDAtikurRahman181-15-2024** [comment]
I have a question. How this check if btc address has balance in it ? Because if I turn off internet connection it keeps running, is this a fake app?

**Comment by adrijano** [comment]
no is not fake app, if address with balance is found it will save in txt if u got right combination of words u can get wallets

**Comment by djmuratb** [comment]
> I have a question. How this check if btc address has balance in it ? Because if I turn off internet connection it keeps running, is this a fake app?



> no is not fake app, if address with balance is found it will save in txt if u got right combination of words u can get wallets

How can the program check the balance without internet? Could you share the codes of the exe file?
